### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [accu-rate/website#11]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by hacklschorsch** [comment]
There isn't much code in this repo besides

- an outdated version of https://github.com/klml/drfrederson (MIT)
- the Skeleton CSS Framework (MIT)
- the Lato free fonts (SIL Open Font License)

the rest is the content of our web site, which intendedly is not put under an open source license. It's content. You can cite it if you want, you have some fair-use leverage, that's it. I would expect anyone forking this website to not use our content.

- Does this answer your question?
- Are you mass-posting this or do you even use a bot? I'm not sure whether to consider this UCE.
